-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.achievements (
  name text NOT NULL UNIQUE,
  description text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['strength'::text, 'consistency'::text, 'volume'::text, 'milestone'::text, 'social'::text, 'special'::text])),
  criteria jsonb NOT NULL,
  icon_name text,
  badge_color text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  points integer DEFAULT 0 CHECK (points >= 0),
  rarity text DEFAULT 'common'::text CHECK (rarity = ANY (ARRAY['common'::text, 'uncommon'::text, 'rare'::text, 'epic'::text, 'legendary'::text])),
  is_active boolean DEFAULT true,
  is_hidden boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT achievements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_coaching_contexts (
  context_key text NOT NULL UNIQUE,
  context_name text NOT NULL,
  description text,
  system_prompt text NOT NULL,
  suggested_model_id uuid,
  coaching_style text CHECK (coaching_style = ANY (ARRAY['supportive'::text, 'challenging'::text, 'analytical'::text, 'motivational'::text])),
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  max_conversation_length integer DEFAULT 20,
  expertise_areas ARRAY DEFAULT '{}'::text[],
  requires_subscription boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_coaching_contexts_pkey PRIMARY KEY (id),
  CONSTRAINT ai_coaching_contexts_suggested_model_id_fkey FOREIGN KEY (suggested_model_id) REFERENCES public.ai_models(id)
);
CREATE TABLE public.ai_conversation_sessions (
  user_id uuid NOT NULL,
  context_id uuid,
  session_title text,
  session_type text CHECK (session_type = ANY (ARRAY['coaching'::text, 'planning'::text, 'analysis'::text, 'support'::text, 'general'::text])),
  conversation_summary text,
  key_insights ARRAY,
  action_items ARRAY,
  completed_at timestamp with time zone,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text, 'archived'::text])),
  message_count integer DEFAULT 0,
  total_tokens_used integer DEFAULT 0,
  total_cost numeric DEFAULT 0,
  user_context jsonb DEFAULT '{}'::jsonb,
  started_at timestamp with time zone DEFAULT now(),
  last_message_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_conversation_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_conversation_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT ai_conversation_sessions_context_id_fkey FOREIGN KEY (context_id) REFERENCES public.ai_coaching_contexts(id)
);
CREATE TABLE public.ai_conversations (
  user_id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  message_type text NOT NULL CHECK (message_type = ANY (ARRAY['user_query'::text, 'ai_response'::text, 'system_message'::text, 'function_call'::text, 'function_response'::text])),
  content text NOT NULL,
  context_data jsonb,
  tokens_used integer,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  session_id uuid,
  model_id uuid,
  message_role text CHECK (message_role = ANY (ARRAY['system'::text, 'user'::text, 'assistant'::text, 'function'::text])),
  function_call jsonb,
  function_response jsonb,
  message_metadata jsonb DEFAULT '{}'::jsonb,
  processing_time_ms integer,
  confidence_score numeric,
  sentiment_score numeric,
  CONSTRAINT ai_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT ai_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT ai_conversations_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.ai_conversation_sessions(id),
  CONSTRAINT ai_conversations_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.ai_models(id)
);
CREATE TABLE public.ai_insights (
  user_id uuid NOT NULL,
  session_id uuid,
  insight_type text NOT NULL CHECK (insight_type = ANY (ARRAY['progress_analysis'::text, 'pattern_recognition'::text, 'goal_assessment'::text, 'performance_trend'::text, 'recovery_analysis'::text, 'form_feedback'::text, 'motivation_boost'::text, 'plateau_identification'::text])),
  category text NOT NULL CHECK (category = ANY (ARRAY['strength'::text, 'endurance'::text, 'recovery'::text, 'motivation'::text, 'technique'::text, 'planning'::text])),
  title text NOT NULL,
  summary text NOT NULL,
  detailed_analysis text,
  key_findings ARRAY,
  data_sources ARRAY,
  time_period_analyzed jsonb,
  statistical_significance numeric,
  actionable_recommendations ARRAY,
  suggested_next_steps ARRAY,
  user_rating integer CHECK (user_rating >= 1 AND user_rating <= 5),
  user_feedback text,
  model_id uuid,
  confidence_score numeric,
  tokens_used integer,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  is_bookmarked boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_insights_pkey PRIMARY KEY (id),
  CONSTRAINT ai_insights_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT ai_insights_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.ai_conversation_sessions(id),
  CONSTRAINT ai_insights_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.ai_models(id)
);
CREATE TABLE public.ai_learning_data (
  user_id uuid NOT NULL,
  session_id uuid,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['recommendation_feedback'::text, 'conversation_rating'::text, 'insight_engagement'::text, 'preference_update'::text, 'behavior_pattern'::text, 'goal_achievement'::text])),
  event_data jsonb NOT NULL,
  user_response jsonb,
  outcome text CHECK (outcome = ANY (ARRAY['positive'::text, 'negative'::text, 'neutral'::text, 'mixed'::text])),
  context_factors jsonb,
  data_quality_score numeric,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contributes_to_training boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_learning_data_pkey PRIMARY KEY (id),
  CONSTRAINT ai_learning_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT ai_learning_data_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.ai_conversation_sessions(id)
);
CREATE TABLE public.ai_model_performance (
  model_id uuid NOT NULL,
  metric_date date NOT NULL,
  average_response_time_ms integer,
  success_rate numeric,
  error_rate numeric,
  timeout_rate numeric,
  average_user_rating numeric,
  recommendation_acceptance_rate numeric,
  conversation_completion_rate numeric,
  cost_per_successful_interaction numeric,
  tokens_per_interaction numeric,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  total_requests integer DEFAULT 0,
  total_tokens_input integer DEFAULT 0,
  total_tokens_output integer DEFAULT 0,
  total_cost numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_model_performance_pkey PRIMARY KEY (id),
  CONSTRAINT ai_model_performance_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.ai_models(id)
);
CREATE TABLE public.ai_models (
  model_name text NOT NULL UNIQUE,
  model_version text NOT NULL,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['openai'::text, 'anthropic'::text, 'google'::text, 'custom'::text])),
  model_type text NOT NULL CHECK (model_type = ANY (ARRAY['chat'::text, 'completion'::text, 'embedding'::text, 'fine_tuned'::text])),
  max_tokens integer NOT NULL,
  context_window integer NOT NULL,
  cost_per_1k_input_tokens numeric NOT NULL,
  cost_per_1k_output_tokens numeric NOT NULL,
  rate_limit_requests_per_minute integer,
  default_max_tokens integer,
  system_prompt text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  supports_functions boolean DEFAULT false,
  supports_streaming boolean DEFAULT false,
  default_temperature numeric DEFAULT 0.7,
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_models_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_system_alerts (
  alert_type text NOT NULL CHECK (alert_type = ANY (ARRAY['high_error_rate'::text, 'cost_threshold_exceeded'::text, 'performance_degradation'::text, 'unusual_usage_pattern'::text, 'model_unavailable'::text, 'rate_limit_exceeded'::text])),
  severity text NOT NULL CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'error'::text, 'critical'::text])),
  title text NOT NULL,
  description text NOT NULL,
  affected_component text,
  alert_data jsonb,
  threshold_value numeric,
  current_value numeric,
  resolved_at timestamp with time zone,
  resolution_notes text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'acknowledged'::text, 'resolved'::text, 'suppressed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_system_alerts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_usage_tracking (
  user_id uuid NOT NULL,
  query_type text NOT NULL,
  query_text text,
  response_text text,
  tokens_used integer NOT NULL CHECK (tokens_used > 0),
  estimated_cost numeric NOT NULL CHECK (estimated_cost >= 0::numeric),
  model_used text NOT NULL,
  response_time_ms integer CHECK (response_time_ms > 0),
  user_rating integer CHECK (user_rating >= 1 AND user_rating <= 5),
  user_feedback text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_usage_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT ai_usage_tracking_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.ai_workout_recommendations (
  user_id uuid NOT NULL,
  session_id uuid,
  recommendation_type text NOT NULL CHECK (recommendation_type = ANY (ARRAY['next_workout'::text, 'exercise_substitution'::text, 'progression_adjustment'::text, 'recovery_suggestion'::text, 'program_modification'::text, 'goal_alignment'::text])),
  title text NOT NULL,
  description text NOT NULL,
  reasoning text,
  recommended_exercises jsonb,
  recommended_parameters jsonb,
  alternative_options jsonb,
  based_on_data jsonb,
  valid_until date,
  user_feedback text CHECK (user_feedback = ANY (ARRAY['accepted'::text, 'rejected'::text, 'modified'::text, 'pending'::text])),
  user_notes text,
  applied_at timestamp with time zone,
  model_id uuid,
  confidence_score numeric,
  tokens_used integer,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_workout_recommendations_pkey PRIMARY KEY (id),
  CONSTRAINT ai_workout_recommendations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT ai_workout_recommendations_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.ai_conversation_sessions(id),
  CONSTRAINT ai_workout_recommendations_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.ai_models(id)
);
CREATE TABLE public.billing_addresses (
  user_id uuid NOT NULL,
  company_name text,
  address_line1 text NOT NULL,
  address_line2 text,
  city text NOT NULL,
  state_province text,
  postal_code text NOT NULL,
  country text NOT NULL,
  tax_id text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT billing_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT billing_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.body_measurements (
  user_id uuid NOT NULL,
  measurement_date date NOT NULL,
  weight_kg numeric CHECK (weight_kg > 0::numeric AND weight_kg < 1000::numeric),
  body_fat_percentage numeric CHECK (body_fat_percentage >= 0::numeric AND body_fat_percentage <= 100::numeric),
  muscle_mass_kg numeric CHECK (muscle_mass_kg >= 0::numeric),
  bone_mass_kg numeric CHECK (bone_mass_kg >= 0::numeric),
  water_percentage numeric CHECK (water_percentage >= 0::numeric AND water_percentage <= 100::numeric),
  visceral_fat_rating integer CHECK (visceral_fat_rating >= 1 AND visceral_fat_rating <= 30),
  metabolic_age integer CHECK (metabolic_age > 0 AND metabolic_age < 150),
  chest_cm numeric CHECK (chest_cm > 0::numeric),
  waist_cm numeric CHECK (waist_cm > 0::numeric),
  hips_cm numeric CHECK (hips_cm > 0::numeric),
  neck_cm numeric CHECK (neck_cm > 0::numeric),
  bicep_left_cm numeric CHECK (bicep_left_cm > 0::numeric),
  bicep_right_cm numeric CHECK (bicep_right_cm > 0::numeric),
  thigh_left_cm numeric CHECK (thigh_left_cm > 0::numeric),
  thigh_right_cm numeric CHECK (thigh_right_cm > 0::numeric),
  forearm_left_cm numeric CHECK (forearm_left_cm > 0::numeric),
  forearm_right_cm numeric CHECK (forearm_right_cm > 0::numeric),
  calf_left_cm numeric CHECK (calf_left_cm > 0::numeric),
  calf_right_cm numeric CHECK (calf_right_cm > 0::numeric),
  measurement_method text,
  notes text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  measurement_conditions jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT body_measurements_pkey PRIMARY KEY (id),
  CONSTRAINT body_measurements_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.discount_code_usage (
  discount_code_id uuid NOT NULL,
  user_id uuid NOT NULL,
  subscription_id uuid,
  discount_amount_cents integer NOT NULL,
  stripe_coupon_id text,
  stripe_promotion_code_id text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  applied_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discount_code_usage_pkey PRIMARY KEY (id),
  CONSTRAINT discount_code_usage_discount_code_id_fkey FOREIGN KEY (discount_code_id) REFERENCES public.discount_codes(id),
  CONSTRAINT discount_code_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT discount_code_usage_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.discount_codes (
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['percentage'::text, 'fixed_amount'::text, 'free_trial'::text])),
  discount_value integer NOT NULL,
  valid_from date NOT NULL,
  valid_until date,
  max_uses integer,
  created_by uuid,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  currency text DEFAULT 'usd'::text,
  max_uses_per_user integer DEFAULT 1,
  current_uses integer DEFAULT 0,
  applicable_plan_ids ARRAY DEFAULT '{}'::uuid[],
  new_customers_only boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discount_codes_pkey PRIMARY KEY (id),
  CONSTRAINT discount_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.exercise_contraindications (
  exercise_id uuid NOT NULL,
  condition_type text NOT NULL,
  condition_description text NOT NULL,
  severity text NOT NULL CHECK (severity = ANY (ARRAY['caution'::text, 'avoid'::text, 'modify'::text])),
  modification_suggestion text,
  alternative_exercise_id uuid,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exercise_contraindications_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_contraindications_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT exercise_contraindications_alternative_exercise_id_fkey FOREIGN KEY (alternative_exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.exercise_form_checkpoints (
  exercise_id uuid NOT NULL,
  checkpoint_order integer NOT NULL,
  phase text NOT NULL CHECK (phase = ANY (ARRAY['setup'::text, 'eccentric'::text, 'bottom'::text, 'concentric'::text, 'top'::text])),
  description text NOT NULL,
  common_error text,
  correction_cue text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  safety_critical boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exercise_form_checkpoints_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_form_checkpoints_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.exercise_search_analytics (
  user_id uuid,
  search_query text NOT NULL,
  search_filters jsonb,
  results_count integer NOT NULL,
  selected_exercise_id uuid,
  search_duration_ms integer,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exercise_search_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_search_analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT exercise_search_analytics_selected_exercise_id_fkey FOREIGN KEY (selected_exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.exercise_sets (
  session_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  planned_exercise_id uuid,
  set_number integer NOT NULL CHECK (set_number > 0),
  weight_kg numeric CHECK (weight_kg >= 0::numeric),
  reps integer CHECK (reps >= 0),
  rpe integer CHECK (rpe >= 1 AND rpe <= 10),
  rest_seconds integer CHECK (rest_seconds >= 0),
  notes text,
  form_rating integer CHECK (form_rating >= 1 AND form_rating <= 5),
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  is_warmup boolean DEFAULT false,
  is_failure boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  tempo text,
  range_of_motion text CHECK (range_of_motion = ANY (ARRAY['full'::text, 'partial'::text, 'extended'::text])),
  technique_rating integer CHECK (technique_rating >= 1 AND technique_rating <= 5),
  effort_level integer CHECK (effort_level >= 1 AND effort_level <= 10),
  rest_quality text CHECK (rest_quality = ANY (ARRAY['poor'::text, 'fair'::text, 'good'::text, 'excellent'::text])),
  set_type text DEFAULT 'working'::text CHECK (set_type = ANY (ARRAY['warmup'::text, 'working'::text, 'drop'::text, 'cluster'::text, 'rest_pause'::text, 'failure'::text])),
  user_id uuid,
  CONSTRAINT exercise_sets_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_sets_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.workout_sessions(id),
  CONSTRAINT exercise_sets_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT exercise_sets_planned_exercise_id_fkey FOREIGN KEY (planned_exercise_id) REFERENCES public.planned_exercises(id)
);
CREATE TABLE public.exercise_tutorial_videos (
  exercise_id uuid NOT NULL,
  title text NOT NULL,
  url text NOT NULL,
  created_by uuid,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT exercise_tutorial_videos_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_tutorial_videos_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT exercise_tutorial_videos_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.exercises (
  name text NOT NULL,
  description text,
  instructions jsonb,
  muscle_groups ARRAY NOT NULL,
  primary_muscle USER-DEFINED NOT NULL,
  equipment ARRAY NOT NULL,
  alternatives ARRAY,
  demo_video_url text,
  form_cues ARRAY,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  difficulty integer DEFAULT 2 CHECK (difficulty >= 1 AND difficulty <= 5),
  is_compound boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  movement_pattern USER-DEFINED,
  complexity USER-DEFINED DEFAULT 'basic'::complexity_enum,
  parent_exercise_id uuid,
  variation_type text,
  common_mistakes ARRAY DEFAULT '{}'::text[],
  progression_exercises ARRAY DEFAULT '{}'::uuid[],
  regression_exercises ARRAY DEFAULT '{}'::uuid[],
  search_vector tsvector,
  search_terms ARRAY DEFAULT '{}'::text[],
  popularity_score integer DEFAULT 0,
  CONSTRAINT exercises_pkey PRIMARY KEY (id),
  CONSTRAINT exercises_parent_exercise_id_fkey FOREIGN KEY (parent_exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.fitness_goals (
  user_id uuid NOT NULL,
  goal_type text NOT NULL CHECK (goal_type = ANY (ARRAY['strength'::text, 'weight_loss'::text, 'weight_gain'::text, 'muscle_gain'::text, 'endurance'::text, 'body_composition'::text, 'performance'::text, 'habit'::text, 'custom'::text])),
  title text NOT NULL,
  description text,
  target_value numeric,
  current_value numeric,
  unit text,
  target_date date,
  completed_date date,
  category text,
  last_updated_value numeric,
  last_updated_date date,
  exercise_id uuid,
  measurement_type text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  start_date date NOT NULL DEFAULT CURRENT_DATE,
  is_active boolean DEFAULT true,
  priority integer DEFAULT 1 CHECK (priority >= 1 AND priority <= 5),
  progress_percentage numeric DEFAULT 0 CHECK (progress_percentage >= 0::numeric AND progress_percentage <= 100::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fitness_goals_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT fitness_goals_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.fitness_stopwords (
  word text
);
CREATE TABLE public.goal_milestones (
  goal_id uuid NOT NULL,
  milestone_name text NOT NULL,
  target_value numeric NOT NULL,
  target_date date,
  achieved_date date,
  achieved_value numeric,
  reward_description text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  is_achieved boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT goal_milestones_pkey PRIMARY KEY (id),
  CONSTRAINT goal_milestones_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.fitness_goals(id)
);
CREATE TABLE public.monthly_ai_usage (
  user_id uuid NOT NULL,
  month_year date NOT NULL,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  total_queries integer DEFAULT 0,
  total_tokens integer DEFAULT 0,
  total_cost numeric DEFAULT 0,
  budget_limit numeric DEFAULT 1.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT monthly_ai_usage_pkey PRIMARY KEY (id),
  CONSTRAINT monthly_ai_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.monthly_reviews (
  user_id uuid NOT NULL,
  review_month date NOT NULL,
  average_rpe numeric,
  strength_gains jsonb,
  goal_progress jsonb,
  recommendations text,
  achievements ARRAY,
  areas_for_improvement ARRAY,
  next_month_focus text,
  ai_generated_at timestamp with time zone,
  tokens_used integer,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workout_count integer NOT NULL DEFAULT 0,
  total_volume_kg numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT monthly_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT monthly_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.payment_history (
  user_id uuid NOT NULL,
  subscription_id uuid,
  amount_cents integer NOT NULL CHECK (amount_cents >= 0),
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'succeeded'::text, 'failed'::text, 'canceled'::text, 'refunded'::text])),
  payment_method text,
  failure_reason text,
  refunded_at timestamp with time zone,
  processed_at timestamp with time zone,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  currency text NOT NULL DEFAULT 'usd'::text,
  refund_amount_cents integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_history_pkey PRIMARY KEY (id),
  CONSTRAINT payment_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT payment_history_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.performance_comparison_groups (
  name text NOT NULL,
  description text,
  criteria jsonb NOT NULL,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT performance_comparison_groups_pkey PRIMARY KEY (id)
);
CREATE TABLE public.plan_feature_limits (
  plan_id uuid NOT NULL,
  feature_id uuid NOT NULL,
  usage_limit integer,
  reset_period text CHECK (reset_period = ANY (ARRAY['daily'::text, 'weekly'::text, 'monthly'::text, 'yearly'::text, 'lifetime'::text])),
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  is_enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT plan_feature_limits_pkey PRIMARY KEY (id),
  CONSTRAINT plan_feature_limits_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id),
  CONSTRAINT plan_feature_limits_feature_id_fkey FOREIGN KEY (feature_id) REFERENCES public.subscription_features(id)
);
CREATE TABLE public.planned_exercises (
  session_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  order_in_session integer NOT NULL CHECK (order_in_session > 0),
  target_sets integer NOT NULL CHECK (target_sets > 0),
  target_reps_min integer CHECK (target_reps_min > 0),
  target_reps_max integer,
  target_rpe integer CHECK (target_rpe >= 1 AND target_rpe <= 10),
  rest_seconds integer CHECK (rest_seconds >= 0),
  notes text,
  progression_scheme jsonb,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT planned_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT planned_exercises_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.workout_plan_sessions(id),
  CONSTRAINT planned_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.progress_metrics (
  user_id uuid NOT NULL,
  metric_date date NOT NULL,
  metric_type text NOT NULL CHECK (metric_type = ANY (ARRAY['strength'::text, 'volume'::text, 'frequency'::text, 'consistency'::text, 'body_composition'::text, 'performance'::text, 'recovery'::text, 'motivation'::text])),
  primary_value numeric NOT NULL,
  secondary_value numeric,
  tertiary_value numeric,
  metric_name text NOT NULL,
  unit text,
  calculation_method text,
  data_points_used integer,
  confidence_score numeric CHECK (confidence_score >= 0::numeric AND confidence_score <= 1::numeric),
  trend_direction text CHECK (trend_direction = ANY (ARRAY['improving'::text, 'declining'::text, 'stable'::text, 'volatile'::text])),
  trend_strength numeric CHECK (trend_strength >= 0::numeric AND trend_strength <= 1::numeric),
  previous_period_value numeric,
  percentage_change numeric,
  percentile_rank integer CHECK (percentile_rank >= 1 AND percentile_rank <= 100),
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT progress_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT progress_metrics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.progressive_overload_records (
  user_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  progression_date date NOT NULL,
  progression_type text NOT NULL CHECK (progression_type = ANY (ARRAY['weight'::text, 'reps'::text, 'sets'::text, 'density'::text, 'range_of_motion'::text])),
  previous_value numeric,
  new_value numeric,
  percentage_increase numeric,
  trigger_reason text,
  user_feedback text,
  success_rating integer CHECK (success_rating >= 1 AND success_rating <= 5),
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT progressive_overload_records_pkey PRIMARY KEY (id),
  CONSTRAINT progressive_overload_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT progressive_overload_records_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.strength_standards (
  exercise_id uuid NOT NULL,
  gender USER-DEFINED NOT NULL,
  bodyweight_kg_min numeric NOT NULL,
  bodyweight_kg_max numeric NOT NULL,
  experience_level USER-DEFINED NOT NULL,
  standard_1rm_kg numeric NOT NULL,
  percentile integer CHECK (percentile >= 1 AND percentile <= 100),
  data_source text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT strength_standards_pkey PRIMARY KEY (id),
  CONSTRAINT strength_standards_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.subscription_analytics (
  subscription_id uuid NOT NULL,
  metric_date date NOT NULL,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workouts_logged integer DEFAULT 0,
  ai_queries_used integer DEFAULT 0,
  custom_workouts_created integer DEFAULT 0,
  data_exports integer DEFAULT 0,
  days_active integer DEFAULT 0,
  features_used ARRAY DEFAULT '{}'::text[],
  session_duration_minutes integer DEFAULT 0,
  estimated_value_delivered numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_analytics_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.subscription_changes (
  user_id uuid NOT NULL,
  current_subscription_id uuid,
  target_plan_id uuid NOT NULL,
  change_type text NOT NULL CHECK (change_type = ANY (ARRAY['upgrade'::text, 'downgrade'::text, 'cancel'::text, 'reactivate'::text])),
  effective_date date,
  proration_amount_cents integer,
  reason text,
  user_feedback text,
  processed_at timestamp with time zone,
  stripe_subscription_schedule_id text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'canceled'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_changes_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_changes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT subscription_changes_current_subscription_id_fkey FOREIGN KEY (current_subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT subscription_changes_target_plan_id_fkey FOREIGN KEY (target_plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.subscription_features (
  feature_key text NOT NULL UNIQUE,
  feature_name text NOT NULL,
  description text,
  category text NOT NULL CHECK (category = ANY (ARRAY['core'::text, 'ai'::text, 'analytics'::text, 'social'::text, 'premium'::text])),
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_features_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscription_pauses (
  subscription_id uuid NOT NULL,
  pause_start_date date NOT NULL,
  pause_end_date date,
  reason text,
  billing_cycle_anchor date,
  prorated_amount_cents integer,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  auto_resume boolean DEFAULT true,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'resumed'::text, 'expired'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_pauses_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_pauses_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.subscription_plans (
  name text NOT NULL,
  description text,
  price_cents integer NOT NULL CHECK (price_cents >= 0),
  interval USER-DEFINED NOT NULL,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  features jsonb NOT NULL DEFAULT '[]'::jsonb,
  max_ai_queries integer DEFAULT 0,
  max_custom_workouts integer DEFAULT 0,
  max_clients integer DEFAULT 0,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  user_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  status USER-DEFINED NOT NULL,
  current_period_start timestamp with time zone NOT NULL,
  current_period_end timestamp with time zone NOT NULL,
  trial_start timestamp with time zone,
  trial_end timestamp with time zone,
  canceled_at timestamp with time zone,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  cancel_at_period_end boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.user_achievements (
  user_id uuid NOT NULL,
  achievement_id uuid NOT NULL,
  progress_value numeric,
  context_data jsonb,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  earned_date date NOT NULL DEFAULT CURRENT_DATE,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_achievements_pkey PRIMARY KEY (id),
  CONSTRAINT user_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT user_achievements_achievement_id_fkey FOREIGN KEY (achievement_id) REFERENCES public.achievements(id)
);
CREATE TABLE public.user_ai_preferences (
  user_id uuid NOT NULL UNIQUE,
  preferred_coaching_style text CHECK (preferred_coaching_style = ANY (ARRAY['supportive'::text, 'challenging'::text, 'analytical'::text, 'motivational'::text])),
  communication_frequency text CHECK (communication_frequency = ANY (ARRAY['minimal'::text, 'moderate'::text, 'frequent'::text, 'intensive'::text])),
  preferred_response_length text CHECK (preferred_response_length = ANY (ARRAY['brief'::text, 'moderate'::text, 'detailed'::text, 'comprehensive'::text])),
  preferred_examples text CHECK (preferred_examples = ANY (ARRAY['personal'::text, 'general'::text, 'scientific'::text, 'motivational'::text])),
  learning_style text CHECK (learning_style = ANY (ARRAY['visual'::text, 'analytical'::text, 'practical'::text, 'social'::text])),
  feedback_sensitivity text CHECK (feedback_sensitivity = ANY (ARRAY['direct'::text, 'gentle'::text, 'balanced'::text, 'encouraging'::text])),
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  focus_areas ARRAY DEFAULT '{}'::text[],
  avoid_topics ARRAY DEFAULT '{}'::text[],
  enable_proactive_suggestions boolean DEFAULT true,
  enable_progress_celebrations boolean DEFAULT true,
  enable_form_reminders boolean DEFAULT true,
  enable_recovery_suggestions boolean DEFAULT true,
  allow_data_analysis boolean DEFAULT true,
  allow_pattern_recognition boolean DEFAULT true,
  allow_predictive_insights boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_ai_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_ai_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.user_feature_usage (
  user_id uuid NOT NULL,
  feature_id uuid NOT NULL,
  last_used_at timestamp with time zone,
  reset_at timestamp with time zone,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  usage_count integer DEFAULT 0,
  period_start timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_feature_usage_pkey PRIMARY KEY (id),
  CONSTRAINT user_feature_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT user_feature_usage_feature_id_fkey FOREIGN KEY (feature_id) REFERENCES public.subscription_features(id)
);
CREATE TABLE public.user_profiles (
  temp_subscription_plan text DEFAULT 'free'::text CHECK (temp_subscription_plan = ANY (ARRAY['free'::text, 'premium'::text, 'coach'::text])),
  temp_subscription_expires timestamp with time zone,
  id uuid NOT NULL,
  email text NOT NULL,
  display_name text NOT NULL,
  avatar_url text,
  weight_kg numeric CHECK (weight_kg > 0::numeric AND weight_kg < 1000::numeric),
  birth_date date,
  gender USER-DEFINED,
  experience_level USER-DEFINED NOT NULL DEFAULT 'untrained'::experience_level_enum,
  fitness_goals ARRAY DEFAULT '{}'::text[],
  available_equipment ARRAY DEFAULT '{}'::text[],
  role USER-DEFINED DEFAULT 'user'::user_role_enum,
  onboarding_completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  height_cm smallint CHECK (height_cm > 0 AND height_cm < 300),
  privacy_data_sharing boolean DEFAULT false,
  privacy_analytics boolean DEFAULT true,
  privacy_ai_coaching boolean DEFAULT true,
  privacy_workout_sharing boolean DEFAULT false,
  privacy_progress_sharing boolean DEFAULT false,
  use_metric boolean DEFAULT false,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_strength_benchmarks (
  user_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  benchmark_date date NOT NULL,
  tested_1rm_kg numeric NOT NULL,
  estimated_1rm_kg numeric,
  bodyweight_kg numeric NOT NULL,
  wilks_score numeric,
  strength_level text,
  percentile_rank integer CHECK (percentile_rank >= 1 AND percentile_rank <= 100),
  notes text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_strength_benchmarks_pkey PRIMARY KEY (id),
  CONSTRAINT user_strength_benchmarks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT user_strength_benchmarks_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.user_workout_customizations (
  user_id uuid NOT NULL,
  template_id uuid NOT NULL,
  customization_data jsonb NOT NULL,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_workout_customizations_pkey PRIMARY KEY (id),
  CONSTRAINT user_workout_customizations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT user_workout_customizations_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.workout_templates(id)
);
CREATE TABLE public.user_workout_progress (
  user_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  last_completed_session_id uuid,
  last_workout_session_id uuid,
  completed_at timestamp with time zone,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  current_phase_number integer NOT NULL DEFAULT 1 CHECK (current_phase_number > 0),
  current_repetition integer NOT NULL DEFAULT 1 CHECK (current_repetition > 0),
  current_day_number integer NOT NULL DEFAULT 1 CHECK (current_day_number > 0),
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_workout_progress_pkey PRIMARY KEY (id),
  CONSTRAINT user_workout_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT user_workout_progress_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.workout_plans(id),
  CONSTRAINT user_workout_progress_last_completed_session_id_fkey FOREIGN KEY (last_completed_session_id) REFERENCES public.workout_plan_sessions(id),
  CONSTRAINT user_workout_progress_last_workout_session_id_fkey FOREIGN KEY (last_workout_session_id) REFERENCES public.workout_sessions(id)
);
CREATE TABLE public.workout_plan_sessions (
  phase_number integer DEFAULT 1 CHECK (phase_number > 0),
  plan_id uuid NOT NULL,
  name text NOT NULL,
  day_number integer NOT NULL CHECK (day_number > 0),
  estimated_duration_minutes integer CHECK (estimated_duration_minutes > 0),
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  phase_repetitions integer NOT NULL DEFAULT 4 CHECK (phase_repetitions > 0),
  CONSTRAINT workout_plan_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT workout_plan_sessions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.workout_plans(id)
);
CREATE TABLE public.workout_plans (
  name text NOT NULL,
  description text,
  type USER-DEFINED NOT NULL,
  frequency_per_week integer CHECK (frequency_per_week >= 1 AND frequency_per_week <= 7),
  duration_weeks integer CHECK (duration_weeks > 0),
  difficulty integer CHECK (difficulty >= 1 AND difficulty <= 5),
  target_experience ARRAY NOT NULL,
  created_by uuid,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  is_template boolean DEFAULT false,
  is_public boolean DEFAULT false,
  tags ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_plans_pkey PRIMARY KEY (id),
  CONSTRAINT workout_plans_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.workout_sessions (
  user_id uuid NOT NULL,
  plan_id uuid,
  session_id uuid,
  name text NOT NULL,
  started_at timestamp with time zone NOT NULL,
  completed_at timestamp with time zone,
  duration_minutes integer,
  total_volume_kg numeric,
  average_rpe numeric,
  notes text,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  sync_status USER-DEFINED DEFAULT 'synced'::sync_status_enum,
  offline_created boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  workout_quality_score numeric,
  estimated_calories_burned integer,
  heart_rate_avg integer,
  heart_rate_max integer,
  perceived_difficulty integer CHECK (perceived_difficulty >= 1 AND perceived_difficulty <= 10),
  environment_factors jsonb DEFAULT '{}'::jsonb,
  workout_tags ARRAY DEFAULT '{}'::text[],
  CONSTRAINT workout_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT workout_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT workout_sessions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.workout_plans(id),
  CONSTRAINT workout_sessions_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.workout_plan_sessions(id)
);
CREATE TABLE public.workout_template_exercises (
  template_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  order_in_workout integer NOT NULL CHECK (order_in_workout > 0),
  superset_group integer,
  target_sets integer NOT NULL CHECK (target_sets > 0),
  rep_range_min integer CHECK (rep_range_min > 0),
  rep_range_max integer,
  rpe_target integer CHECK (rpe_target >= 1 AND rpe_target <= 10),
  rest_seconds integer CHECK (rest_seconds >= 0),
  intensity_percentage numeric,
  tempo_prescription text,
  range_of_motion_notes text,
  technique_focus ARRAY,
  progression_scheme jsonb,
  conditions jsonb,
  alternatives ARRAY,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  exercise_type text DEFAULT 'main'::text CHECK (exercise_type = ANY (ARRAY['warmup'::text, 'main'::text, 'accessory'::text, 'cooldown'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_template_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT workout_template_exercises_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.workout_templates(id),
  CONSTRAINT workout_template_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.workout_templates (
  name text NOT NULL,
  description text,
  created_by uuid,
  template_type text NOT NULL CHECK (template_type = ANY (ARRAY['system'::text, 'user'::text, 'coach'::text, 'community'::text])),
  target_experience ARRAY NOT NULL,
  estimated_duration_minutes integer CHECK (estimated_duration_minutes > 0),
  difficulty_rating numeric CHECK (difficulty_rating >= 1.0 AND difficulty_rating <= 5.0),
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  muscle_focus ARRAY DEFAULT '{}'::muscle_group_enum[],
  equipment_required ARRAY DEFAULT '{}'::equipment_enum[],
  tags ARRAY DEFAULT '{}'::text[],
  is_public boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  usage_count integer DEFAULT 0,
  rating_avg numeric DEFAULT 0,
  rating_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_templates_pkey PRIMARY KEY (id),
  CONSTRAINT workout_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);