[build]
  command = "npm run build:web"
  publish = "dist"
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/service-worker.js"
  [headers.values]
  Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.json"
  [headers.values]
  Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"
